### ISSUE TITLE
Trailing commas should be highlighted as a syntax error

### ISSUE THREAD

**Issue by jaikdean** [atom/language-json#11]
Trailing commas such as on line 3 below should be highlighted as syntax errors.

```json
{
  "foo": 1,
  "bar": 2,
}
```

**Comment by Morriz** [comment]
yeah...major flaw, that costs a lot of time if not reported by this module ;(

**Comment by Morriz** [comment]
and definitely not an 'enhancement'...MAJOR bug since invalid json is not detected

**Comment by 50Wliu** [comment]
The main purpose of language packages is to correctly highlight valid syntax, and not to point out invalid syntax, though that is an added bonus.  That's more of a job for linters.

**Comment by Morriz** [comment]
I see. Will look for one then... tnx

**Comment by floatingLomas** [comment]
If I miss a comma at the end of a key-value pair that is not the last one, it highlights the following comma, so I don't think it's unreasonable to highlight a closing bracket (`}` or `]`) if it follows a comma.
