### ISSUE TITLE
JSON files that allow comments.

### ISSUE THREAD

**Issue by konstantin-popov** [atom/language-json#12]
Although AFAIK JSON spec doesn't allow comments, some filetypes processed by this package do allow them (mostly config files, ```.jshintrc``` as an example), and they can be rather userful. Now comments in such files are highlighted as errors. 
Maybe it's worth adding a package setting for this?

**Comment by lee-dohm** [comment]
I would say that if they diverge from JSON, then they aren't actually JSON and should have their own language package ... no matter how similar they are to JSON in the main. It's kind of like if we used the JavaScript language package to highlight C files. Sure, there is a lot of overlap and things would look *mostly* right ... but it still isn't the right thing to do.

**Comment by konstantin-popov** [comment]
@lee-dohm, so do you think this is worth creating a separate package or better just forget it?

**Comment by lee-dohm** [comment]
I think that if this is a feature you desire, then yes, it is worth creating a separate package for it. It wouldn't be an Atom core package, but it doesn't have to be.

**Comment by konstantin-popov** [comment]
Thanks.

**Comment by miguelamello** [comment]
Hi There. I disagree about another separate package to deal with comments in json. It is right that comments does not stick to specification, however, in real everyday life, we do need comments in json, mainly due to code colaboration. I see no problem about language-json package dealing with comments.

**Comment by mgcrea** [comment]
:+1:, I'd love to have a setting where I could tick a box to allow comments. Most of my JSON-like files I'm working with contains comments & editing them in Atom is a pain today, as it breaks syntax highlighting.

For instance: https://github.com/airbnb/javascript/blob/master/linters/.eslintrc

**Comment by clintwood** [comment]
:+1:

**Comment by jacobdufault** [comment]
+1, if you think about it from a usability perspective it makes sense for this to be an option.

**Comment by clintwood** [comment]
@jacobdufault, @mgcrea, @konstantin-popov, @miguelamello, I've forked this package and added said features.  I agree that it is not ideal to have a separate package...  Please see:

https://atom.io/packages/language-json-comments

@izuzak, I can do a PR if you wish but I think in light of your decision above it would probably not be accept it.  The changes are really quite minor.

**Comment by izuzak** [comment]
@clintwood I don't think I've made any decisions or comments on this thread. Can you clarify what you're referring to?

**Comment by clintwood** [comment]
@izuzak, sorry wrong person! :) I meant @konstantin-popov, updating above comment...

**Comment by jacobdufault** [comment]
@clintwood, based on #28 it sounds like a PR would be accepted.

**Comment by clintwood** [comment]
I'll try one and see where it goes...
