### ISSUE TITLE
show json path of cursor

### ISSUE THREAD

**Issue by floverdevel** [atom/language-json#13]
It would be nice to display the json path of the element at the cursor position (or on mouseover maybe).
see https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en for an example (bottom of first image of the slideshow)

* given this json data :
```javascript
{
  "id": "666",
  "title": "Hello",
  "pages": [
    {
      "number": 1,
    },
    {
      "number": 2,
    }
  ]
}
```

* when the cursor is at position
 * "number": \<cursor\>2
* then expected result
 * pages[1].number

**Comment by slang800** [comment]
That would be really cool, but it's a bit out-of-scope for a language package. Perhaps you could make it into a separate package and release it on https://atom.io/packages?

**Comment by lee-dohm** [comment]
I agree, this sounds like a great idea for a package.

**Comment by floverdevel** [comment]
Sounds like a good idea.

I should follow these guidelines and respect this api?
https://atom.io/docs/api/v0.204.0/PackageManager

**Comment by lee-dohm** [comment]
I'm not sure what you're asking @floverdevel. You can find documentation on how to write a package here:

https://atom.io/docs/latest/hacking-atom-tools-of-the-trade

**Comment by floverdevel** [comment]
Thank you Lee, that's what i was looking for :)



1100101000111101
" Unfortunately, no one can be told what The Matrix is.  You have to see it
for yourself. "

**Comment by kevinsawicki** [comment]
Thanks, closing this out since this is a great package idea but not something that will be added to this package.
