### ISSUE TITLE
Comments should not be highlighted

### ISSUE THREAD

**Issue by miguelamello** [atom/language-json#22]
Hi There,

I got the need to comment my json files. Well, no problem about this regarding package itself. However, all comments are highlighted by language-json, and this is not eye catching. I think it confuses the readness of content. My suggestion is for language-json does highlight anything between comments, aka "/* ... */". 

Best regards,

Miguel Mello

**Comment by izuzak** [comment]
Thanks for the suggestion, @miguelamello. There's been some previous discussion on this in https://github.com/atom/language-json/issues/12. Could you add a comment to that thread to express interest in this feature (even though the issue is closed)? Having everything in one place is always helpful.

**Comment by izuzak** [comment]
And if I've misunderstood your suggestion -- please feel free to clarify. Sharing more details would be helpful (e.g. a screenshot and a clearer explanation about what you'd like to see).
