### ISSUE TITLE
Code folding is fooled by bad indentation

### ISSUE THREAD

**Issue by alflanagan** [atom/language-json#32]
It appears the code folding functionality is based on indentation (?) rather than syntax:

    {
      "level": "first",
      "some_value": "value",
      "children": [
        {
          "level": "second",
          "some-value": "some",
      "another-list": [
          ]
        }]}

If I fold "children" above, "another-list" should be folded in, but is not

    {
      "level": "first",
      "some_value": "value",
      "children": [
      "another-list": [
          ]
        }]}

**Comment by alflanagan** [comment]
OK, on actually reviewing the repository, it's clear this is the wrong place for this. Not sure what the correct place is, but I'll try to find it. Sorry for the inconvenience.

**Comment by udayms** [comment]
Was this issue fixed eventually? I still see it happening...
