### ISSUE TITLE
.json5

### ISSUE THREAD

**Issue by terraqout** [atom/language-json#33]
Hi guys. Thanks for your work.

I'm using pm2 and it's configuration file called *.json5. Now I treat it like a general json with file-type plugin.

If this is regular json, can I create PR with additional json5 selector? If thing are more complicated any clarification appreciated.

**Comment by 50Wliu** [comment]
> If this is regular json, can I create PR with additional json5 selector?

Yep!

**Comment by thomasjo** [comment]
JSON5 is not normal JSON though: http://json5.org/

**Comment by elifoster** [comment]
There is a [JSON5 package](https://github.com/wiredmax/language-json5) for Atom, however it doesn't look like it's been updated in the past several months, so it may or may not work. It's worth a shot, though, @terraqout.

**Comment by 50Wliu** [comment]
JSON5 is now supported by language-javascript: see atom/language-javascript#266.
