### ISSUE TITLE
string/identifier background issues

### ISSUE THREAD

**Issue by q42jaap** [atom/language-json#34]
<img width="435" alt="screen shot 2015-10-04 at 16 20 50" src="https://cloud.githubusercontent.com/assets/114642/10268279/e7c29a74-6ab3-11e5-9c88-4788db8fbc86.png">
I have disabled all community packages, running atom 1.0.19.

**Comment by MaximSokolov** [comment]
The issue can be closed as it isn't a valid JSON. The following is:
```json
{
  "id": 123,
  "somekey": "value"
}
```
