### ISSUE TITLE
.eslintrc is actually yaml.

### ISSUE THREAD

**Issue by KenPowers** [atom/language-json#36]
`.eslintrc` files are loaded by [`loadLegacyConfigFile`](https://github.com/eslint/eslint/blob/756b2790bf54e9f2df9a93dcfd40b8153a814e6a/lib/config/config-file.js#L100-L120) which loads `yaml` (which happens to be a superset of `json`). The file is only explicitly parsed as `json` when it ends in `.json` (i.e., `.eslintrc.json`) as seen [here](https://github.com/eslint/eslint/blob/756b2790bf54e9f2df9a93dcfd40b8153a814e6a/lib/config/config-file.js#L199).

Compare `json` syntax highlighting:

![json](https://cloud.githubusercontent.com/assets/174864/11232761/86429d28-8d84-11e5-94d9-7160242fb59d.png)

vs `yaml` syntax highlighting:

![yaml](https://cloud.githubusercontent.com/assets/174864/11232771/923a4fd6-8d84-11e5-9348-8dc7b52319a0.png)

And while I haven't verified this, I believe this can lead to issues if a package is expecting a `.eslintrc` file to be strict JSON based on Atom thinking it is JSON.

See #12, #29.

**Comment by elifoster** [comment]
Looking at the [docs for ESLint](http://eslint.org/docs/user-guide/configuring.html), that isn't true. I'm not 100% sure, but looking at the examples they use JSON syntax much more than YAML. However, it may just support both JSON and YAML, which makes adding support in Atom... terrible.

**Comment by KenPowers** [comment]
Quoting that page:

> Configuration Files - use a JSON or YAML file to specify configuration information for an entire directory and all of its subdirectories. This can be in the form of an .eslintrc file or an eslintConfig field in a package.json file, both of which ESLint will look for and read automatically, or you can specify a configuration file on the command line.

They're saying JSON *or YAML* in order to not confuse people who aren't aware that [valid JSON is valid YAML](https://en.wikipedia.org/wiki/YAML#JSON). Given that, as I pointed out, `.eslintrc` is run through `js-yaml` with no checks as to its file-type, it makes sense to highlight it as YAML.

**Comment by KenPowers** [comment]
Wondering if the Atom team actually wants this fixed. I'll submit pull requests if there is interest. It makes sense to me to highlight files according to how they will be parsed by the tooling. Highlighting errors like this are somewhat annoying:

![image](https://cloud.githubusercontent.com/assets/174864/11538154/9774003a-98ee-11e5-9c7b-b551470b110a.png)

**Comment by 50Wliu** [comment]
@KenPowers Yup we're interested - feel free to make a PR!  That's why the `beginner` and `help-wanted` labels are attached :).

**Comment by elifoster** [comment]
@50Wliu How does Atom handle a file type being in multiple different language highlighters?

**Comment by 50Wliu** [comment]
It doesn't.  Atom chooses the first match and stops.  This is a large issue with Ruby, C/C++/Obj-C/etc. and some other languages since the language chosen for common file extensions all depends on the package load order (so Obj-C header files are commonly highlighted as C).

**Comment by elifoster** [comment]
Hm, alright, that's what I expected. What would be awesome is a config option for first selections, when there are known file type conflicts. It'd be helpful for people who develop, for example, in Objective C but not C, but always have to change the highlighting to Objective C.

**Comment by dwelle** [comment]
Should this really be considered as fixed? My JSON eslintrc is highlighted incorrectly if the grammar is set to YAML.

e.g.

![image](https://cloud.githubusercontent.com/assets/5153846/20355172/ba8862be-ac20-11e6-9c72-8a43c002fb58.png)

**Comment by jlmakes** [comment]
I'm with you @dwelle, I'm looking for a way to default my `.eslintrc` files to open as JSON because like you, I am not using YAML.

**Comment by mnquintana** [comment]
As of the latest ESLint, [`.eslintrc` files are deprecated in favor of `.eslintrc.json` or `.eslintrc.yaml`](http://eslint.org/docs/user-guide/configuring#configuration-file-formats), which totally resolves this ambiguity – I'd recommend upgrading to a version of ESLint that supports the new filenames. Since this seems like the right way forward, I'm going to mark this as `wontfix`.
