### ISSUE TITLE
Support for .jsonld files

### ISSUE THREAD

**Issue by alexnorton** [atom/language-json#41]
According to this [Wikipedia page](https://en.wikipedia.org/wiki/JSON-LD) the extension for JSON-LD files is `.jsonld`, so it seems that this should be added to the list of those recognised by this package.

**Comment by chharvey** [comment]
Syntax coloring for *.jsonld* files is supported, but it still uses classname `.syntax--json`. Would it be appropriate to use `.syntax--jsonld` for the *.jsonld* filetype? That way, users could differentiate styles between *.json* and *.jsonld* files.

**Comment by 50Wliu** [comment]
@chharvey No, we currently do not support that.  You would need a different language package, `language-jsonld`.
