### ISSUE TITLE
Pasting in code is not indented correctly

### ISSUE THREAD

**Issue by dmnd** [atom/language-json#6]
If I start with this:

``` json
{
  "data": [{
    "key": "value"
  }, {
    "key": "value"
  }]
}
```

and copy the contents of the array, then insert the cursor immediately before the closing brackets, then paste, I get this:

``` json
{
  "data": [{
    "key": "value"
  }, {
    "key": "value"
  }, {
    "key": "value"
    }, {
      "key": "value"
      }]
}
```

Notice the bad indentation on new objects.

I have auto indentation on:

![image](https://cloud.githubusercontent.com/assets/4427/5408738/05eedade-8195-11e4-951f-d5e3111a6482.png)

**Comment by wcandillon** [comment]
I'm very interested about this issue. It happens on other modes and I have no idea why.

**Comment by muppetjones** [comment]
The indent problem is atom-wide (since 0.192 as far as I can tell): [here](https://github.com/atom/atom/issues/6655).

**Comment by 50Wliu** [comment]
Cannot reproduce on Atom 1.15.0-dev-d5785a1, so closing.  Please comment here if it's still an issue.
