### ISSUE TITLE
No highlighting on JSON file if it contains long line

### ISSUE THREAD

**Issue by wesinator** [atom/language-json#70]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

JSON highlighting is not applied on JSON file that contains long lines, even though grammar selector set to JSON.

### Steps to Reproduce

1. JSON file example [json_nohighlight_example.zip](https://github.com/atom/language-json/files/2881371/json_nohighlight_example.zip) (HAR content)
2. Open in atom

**Expected behavior:** JSON highlighting applied where possible, observing long lines limit.

**Actual behavior:** No JSON highlighting applied, even though grammar selector set JSON.
![image](https://user-images.githubusercontent.com/5124946/53037438-38fe7280-3448-11e9-9bf1-b4d825ad3392.png)

VS code highlights and shows message `Tokenization is skipped for lines longer than 20k characters for performance reasons.`

**Reproduces how often:** Always

### Versions

```
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.17.2
```

**Comment by rsese** [comment]
Thanks for the report - there are known limitations for languages without a Tree-sitter grammar in Atom /cc https://github.com/atom/atom/issues/11232#issuecomment-336731653.  Looks like the file is 6MB, so over the 2MB limit.

There's a pull request to add a Tree-sitter grammar for language-json here if you want to subscribe: https://github.com/atom/language-json/pull/68.
