### ISSUE TITLE
Atom 1.47.0 | JSON - bug in his syntax

### ISSUE THREAD

**Issue by duboloms** [atom/language-json#80]
Now, in last atom version (1.47.0) json syntax bug:

![image](https://user-images.githubusercontent.com/54753636/82467283-2ef37580-9aca-11ea-820e-f83c26562eb7.png)

Must be:

![image](https://i.github-camo.com/0631bf882e84b803601df5cd7833285eb64a3a0a/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4c756b617348656368656e6265726765722f61746f6d2d6a736f6e2d656469746f722f6d61737465722f73637265656e73686f742e706e67)

Yet image:

![image](https://i.stack.imgur.com/QluiS.png)

**Comment by zckrs** [comment]
I think all user with Atom 1.47.0 have this annoying problem.

How can we help to fix this ?

**Comment by d-thomson** [comment]
Is there a quick config fix for this? or a way to rollback the atom version?

**Comment by duboloms** [comment]
@zckrs I'm think atom developers making new version with patches NOW. Otherwise, they will feel bad from our reports

**Comment by rajivshah3** [comment]
![image](https://user-images.githubusercontent.com/19519564/82782310-07820d00-9e2a-11ea-8458-46fc31f5bb0c.png)

@maxbrunsfeld I noticed you maintain https://github.com/tree-sitter/tree-sitter-json. I only see this issue when I check "Use Tree Sitter Parsers". Should this issue be transferred to your repo?

**Comment by zckrs** [comment]
Any news about this ?

Where you find checkbox "Use Tree Sitter Parsers" in settings ?

**Comment by edawpr** [comment]
@zckrs  I found the setting in Core at the bottom of all settings. I removed it and it fixed the issue. 

Now I gotta find out if I should keep it unchecked or check it again when a new Atom version is available...

**Comment by zckrs** [comment]
This solution is just a workaround. And it disable color syntax for Typescript.

Can you reopen this issue @duboloms ?
